package gayhearts.ocsedna;

import java.util.Map;
import static java.util.Map.entry;

public class KeyCodes {
	public final static char   special_offset = 256;
	public final static char[] lwjgl_keys = {
		'\0',
		0x1B, // ESC
		'1',
		'2',
		'3',
		'4',
		'5',
		'6',
		'7',
		'8',
		'9',
		'0',

		'-',
		'=',
		'\b',
		'\t',

		'q',
		'w',
		'e',
		'r',
		't',
		'y',
		'u',
		'i',
		'o',
		'p',

		'[',
		']',
		special_offset+28, //KEY_RETURN
		'\0', //KEY_LCONTROL, handle seperately?

		'a',
		's',
		'd',
		'f',
		'g',
		'h',
		'j',
		'k',
		'l',

		';',
		'\'',
		'`',
		'\0', //KEY_LSHIFT, handle seperately?
		'\\',

		'z',
		'x',
		'c',
		'v',
		'b',
		'n',
		'm',

		',',
		'.',
		'/',
		'\0', //KEY_RSHIFT, handle seperately?
		'*',  //KEY_MULTIPLY,
		'\0', //unix_keys.KEY_LMENU,
		' ',
		'\0', //KEY_CAPITAL, is this CAPS_LOCK?
		'\0', //unix_keys.KEY_F1,
		'\0', //unix_keys.KEY_F2,
		'\0', //unix_keys.KEY_F3,
		'\0', //unix_keys.KEY_F4,
		'\0', //unix_keys.KEY_F5,
		'\0', //unix_keys.KEY_F6,
		'\0', //unix_keys.KEY_F7,
		'\0', //unix_keys.KEY_F8,
		'\0', //unix_keys.KEY_F9,
		'\0', //unix_keys.KEY_F10,
		'\0', //unix_keys.KEY_NUMLOCK,
		'\0', //unix_keys.KEY_SCROLL,
		'7', //unix_keys.KEY_NUMPAD7,
		'8', //unix_keys.KEY_NUMPAD8,
		'9', //unix_keys.KEY_NUMPAD9,
		'-', //unix_keys.KEY_SUBTRACT,
		'4', //unix_keys.KEY_NUMPAD4,
		'5', //unix_keys.KEY_NUMPAD5,
		'6', //unix_keys.KEY_NUMPAD6,
		'+', //unix_keys.KEY_ADD,
		'1', //unix_keys.KEY_NUMPAD1,
		'2', //unix_keys.KEY_NUMPAD2,
		'3', //unix_keys.KEY_NUMPAD3,
		'0', //unix_keys.KEY_NUMPAD0,
		'.', //unix_keys.KEY_DECIMAL,

		'\0',
		'\0',
		'\0',

		'\0', //unix_keys.KEY_F11,
		'\0', //unix_keys.KEY_F12,

		'\0',
		'\0',
		'\0',
		'\0',
		'\0',
		'\0',
		'\0',
		'\0',
		'\0',
		'\0',
		'\0',

		'\0', //unix_keys.KEY_F13,
		'\0', //unix_keys.KEY_F14,
		'\0', //unix_keys.KEY_F15,
		'\0', //unix_keys.KEY_F16,
		'\0', //unix_keys.KEY_F17,
		'\0', //unix_keys.KEY_F18,

		'\0',
		'\0',
		'\0',
		'\0',
		'\0',
		'\0',
		'\0', //unix_keys.KEY_KANA,
		'\0', //unix_keys.KEY_F19,
		'\0',
		'\0',
		'\0',
		'\0',
		'\0',
		'\0',
		'\0',
		'\0', //unix_keys.KEY_CONVERT,
		'\0',
		'\0', //unix_keys.KEY_NOCONVERT,
		'\0',
		'¥', //unix_keys.KEY_YEN,
		'\0',
		'\0',
		'\0',
		'\0',
		'\0',
		'\0',
		'\0',
		'\0',
		'\0',
		'\0',
		'\0',
		'\0',
		'\0',
		'\0',
		'\0',
		'=', //unix_keys.KEY_NUMPADEQUALS,
		'\0',
		'\0',
		'\0', //unix_keys.KEY_CIRCUMFLEX,
		'\0', //unix_keys.KEY_AT,
		':',
		'_',
		'\0', //unix_keys.KEY_KANJI,
		'\0', //unix_keys.KEY_STOP,
		'\0', //unix_keys.KEY_AX,
		'\0', //unix_keys.KEY_UNLABELED,
		'\0',
		'\0',
		'\0',
		'\0',
		'\r', //KEY_NUMPADENTER,
		'\0', //unix_keys.KEY_RCONTROL,
		'\0',
		'\0',
		'\0',
		'\0',
		'\0',
		'\0',
		'\0',
		'\0',
		'\0',
		'\0', //unix_keys.KEY_SECTION,
		'\0',
		'\0',
		'\0',
		'\0',
		'\0',
		'\0',
		'\0',
		'\0',
		'\0',
		'\0',
		'\0',
		',', //unix_keys.KEY_NUMPADCOMMA,
		'\0',
		'/', //unix_keys.KEY_DIVIDE,
		'\0',
		'\0', //unix_keys.KEY_SYSRQ,
		'\0', //unix_keys.KEY_RMENU,
		'\0',
		'\0',
		'\0',
		'\0',
		'\0',
		'\0',
		'\0',
		'\0',
		'\0',
		'\0',
		'\0',
		'\0', //unix_keys.KEY_FUNCTION,
		'\0', //unix_keys.KEY_PAUSE,
		'\0',
		'\0', //unix_keys.KEY_HOME,
		special_offset+200, //unix_keys.KEY_UP,
		'\0', //unix_keys.KEY_PRIOR,
		'\0',
		special_offset+203, //unix_keys.KEY_LEFT,
		'\0',
		special_offset+205, //unix_keys.KEY_RIGHT,
		'\0',
		'\0', //unix_keys.KEY_END,
		special_offset+208, //unix_keys.KEY_DOWN,
		'\0', //unix_keys.KEY_NEXT,
		'\0', //unix_keys.KEY_INSERT,
		'\0', //unix_keys.KEY_DELETE,
		'\0',
		'\0',
		'\0',
		'\0',
		'\0',
		'\0',
		'\0', //unix_keys.KEY_CLEAR,
		'\0', //unix_keys.KEY_LMETA,
		'\0', //unix_keys.KEY_RMETA,
		'\0', //unix_keys.KEY_APPS,
		'\0', //unix_keys.KEY_POWER,
		'\0', //unix_keys.KEY_SLEEP,
	};
}
